import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Common/Header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/ui/Common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
     <html lang="en">

<body
  className={`${geistMono.variable} font-sans antialiased`}>
    <div className="relative flex min-h-screen
    flex-col">
  <Header/>
<main className="flex-1"> {children}</main> 
 <Footer/>
  </div>
</body>
</html>
    </ClerkProvider>
  );
}
